src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
	use TimestampableEntity;

	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $title;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="videos")
	 * @ORM\JoinColumn(nullable=false)
	 * @Assert\NotBlank(message="you are the author")
	 */
	private $author;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	private $videoContent;

	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 */
	private $publishedAt;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\Tutorial", inversedBy="videos")
	 */
	private $Tutorial;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="video", fetch="EXTRA_LAZY")
	 * @ORM\OrderBy({"createdAt" = "DESC"})
	 */
	private $comments;

	/**
	 * @ORM\Column(type="string", length=180, nullable=true)
	 * @Gedmo\Slug(fields={"title"})
	 */
	private $slug;

	/**
	 * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="videos")
	 */
	private $tags;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $videoPath;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imagePath;

	public function __construct()
                  	{
                  		$this->comments = new ArrayCollection();
                  		$this->tags = new ArrayCollection();
                  	}


	public function getId(): ?int
                  	{
                  		return $this->id;
                  	}

	public function getTitle(): ?string
                  	{
                  		return $this->title;
                  	}

	public function setTitle(string $title): self
                  	{
                  		$this->title = $title;
                  
                  		return $this;
                  	}

	public function getAuthor(): ?User
                  	{
                  		return $this->author;
                  	}

	public function setAuthor(?User $author): self
                  	{
                  		$this->author = $author;
                  
                  		return $this;
                  	}

	public function getVideoContent(): ?string
                  	{
                  		return $this->videoContent;
                  	}

	public function setVideoContent(?string $videoContent): self
                  	{
                  		$this->videoContent = $videoContent;
                  
                  		return $this;
                  	}

	public function getPublishedAt(): ?\DateTimeInterface
                  	{
                  		return $this->publishedAt;
                  	}

	public function setPublishedAt(?\DateTimeInterface $publishedAt): self
                  	{
                  		$this->publishedAt = $publishedAt;
                  
                  		return $this;
                  	}

	public function getTutorial(): ?Tutorial
                  	{
                  		return $this->Tutorial;
                  	}

	public function setTutorial(?Tutorial $Tutorial): self
                  	{
                  		$this->Tutorial = $Tutorial;
                  
                  		return $this;
                  	}

	/**
	 * @return Collection|Comment[]
	 */
	public function getExistingComments(): Collection
                  	{
                  		$criteria = VideoRepository::existingCommentsCriteria();
                  
                  		return $this->comments->matching($criteria);
                  	}

	/**
	 * @return Collection|Comment[]
	 */
	public function getComments(): Collection
                  	{
                  		return $this->comments;
                  	}

	public function addComment(Comment $comment): self
                  	{
                  		if (!$this->comments->contains($comment)) {
                  			$this->comments[] = $comment;
                  			$comment->setVideo($this);
                  		}
                  
                  		return $this;
                  	}

	public function removeComment(Comment $comment): self
                  	{
                  		if ($this->comments->contains($comment)) {
                  			$this->comments->removeElement($comment);
                  			// set the owning side to null (unless already changed)
                  			if ($comment->getVideo() === $this) {
                  				$comment->setVideo(null);
                  			}
                  		}
                  
                  		return $this;
                  	}

	public function getSlug(): ?string
                  	{
                  		return $this->slug;
                  	}

	public function setSlug(string $slug): self
                  	{
                  		$this->slug = $slug;
                  
                  		return $this;
                  	}

	/**
	 * @return Collection|Tag[]
	 */
	public function getTags(): Collection
                  	{
                  		return $this->tags;
                  	}

	public function addTag(Tag $tag): self
                  	{
                  		if (!$this->tags->contains($tag)) {
                  			$this->tags[] = $tag;
                  		}
                  
                  		return $this;
                  	}

	public function removeTag(Tag $tag): self
                  	{
                  		if ($this->tags->contains($tag)) {
                  			$this->tags->removeElement($tag);
                  		}
                  
                  		return $this;
                  	}

    public function getVideoPath(): ?string
    {
        return $this->videoPath;
    }

    public function setVideoPath(?string $videoPath): self
    {
        $this->videoPath = $videoPath;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(?string $imagePath): self
    {
        $this->imagePath = $imagePath;

        return $this;
    }

	public function __toString(): string
	{
		return $this->title;
	}


	/*public function validate(ExecutionContextInterface $context, $payload)
	{
		if (stripos($this->getTitle(),'fuc') !== false) {
			$context->buildViolation('you can use that type of words here...')
				->atPath('title')
				->addViolation()
			;
		}
	}*/
}

src/Form/VideoType.php
<?php
/**
 * Created by PhpStorm.
 * User: torop
 * Date: 07-Jun-19
 * Time: 12:30 PM
 */

namespace App\Form;

use App\Entity\User;
use App\Entity\Video;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;


class VideoType extends AbstractType
{
	/**
	 * @var UserRepository
	 */
	private $userRepository;

	public function __construct(UserRepository $userRepository)
	{

		$this->userRepository = $userRepository;
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$article = $options['data'] ?? null;
		$isEdit = $article && $article->getId();

		$builder
			->add('title', TextType::class, [
				'help' => 'Here goes your video title'
			])
			->add('videoContent', null, [
				'rows' => 10
				//'attr' => ['rows' => 10]
			])
			->add('author', UserDropdownTextType::class, [
				'disabled' => $isEdit
			])
		;
		/*EntityType::class, array(
			'class' => User::class,
			'choice_label' => 'firstName',
			'placeholder' => 'choose an author',
			'choices' => $this->userRepository
				->findAllFirstNamesInOrder()*/
		if ($options['published_at']) {
			$builder->add('publishedAt', null, [
				'widget' => 'single_text'
			]);
		}

	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => Video::class,
			'published_at' => false,
		]);
	}
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Entity\Comment;
use App\Repository\CommentRepository;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VideoController extends AbstractController
{
	/**
	 * @Route("/", name="app_homepage")
	 */
	public function homepage(VideoRepository $repository)
	{
		$videos = $repository->findAll();

		return $this->render('video/homepage.html.twig', [
			'videos' => $videos
		]);
	}

	//use for path {{ patg('app_video_show', {slug: 'text'})}}

	/**
	 * @Route("/tici/videos/{slug}", name="app_video_show")
	 */
	public function show($slug, EntityManagerInterface $entityManager)
	{
		$repository = $entityManager->getRepository(Video::class);
		/** @var @var Video $video */
		$video = $repository->findOneBy(['slug' => $slug]);

		return $this->render('video/show.html.twig', [
			'video' => $video
		]);
	}

	/**
	 * @Route("/tici/video/{id}", name="app_video_get")
	 */
	public function getVideo($id, EntityManagerInterface $entityManager)
	{
		$repository = $entityManager->getRepository(Video::class);
		/** @var @var Video $video */
		$video = $repository->findVideoById($id);
		//dump(json_encode($video, true));
		//dd($video);
		return new JsonResponse([
			'content' => json_encode($video, true),
		]);

	}

}

templates/video/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Videos{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }
        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <h1 class="text-center" style="margin-top: 7%; color: #007bff">Welcome to TICI !</h1>
    <h2 class="text-center">Lorem Ipsum</h2>

    <div class="container">
        <div class="col-md-12" style="margin-top: 7%">
            <p class="text-center">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus volutpat tortor massa, at vulputate
                purus accumsan et. Suspendisse aliquet hendrerit placerat. Ut feugiat quam a tortor convallis, at
                sagittis purus lacinia. Aliquam sodales convallis risus, in finibus magna porttitor a. Aliquam magna
                odio, tincidunt non velit eget, facilisis hendrerit nulla. Sed congue faucibus dui eget dictum. Ut
                consectetur, urna et pharetra elementum, ante justo mattis arcu, vitae faucibus nibh eros in lorem.
                Quisque vitae lectus quis arcu commodo suscipit. Maecenas facilisis tortor in tellus egestas, a
                hendrerit magna vulputate. Phasellus in purus eget justo accumsan sollicitudin. Ut sit amet lacinia
                lorem. Aenean semper, orci sed pellentesque cursus, massa est rhoncus libero, vitae porttitor odio
                purus euismod purus.
            </p>
        </div>
    </div>


{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block body %}
<script src="jstree/jstree.min.js"></script>
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>
    <div id="jstree_demo_div"></div>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/Projects/tici-back-end/src/Controller/VideoController.php'|file_link(0) }}">src/Controller/VideoController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/Projects/tici-back-end/templates/video/index.html.twig'|file_link(0) }}">templates/video/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ video.title }}{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
    <span>
        {{ video.publishedAt ? video.publishedAt|ago : 'not listed' }}
    </span>
        {% for  comment in video.existingComments %}
            <div>
                {% if comment.isDeleted %}
                    <div>
                        <span class="fa fa-close"></span> Comment has been removed
                    </div>
                {% endif %}
                <span>
                    {{ comment. userName }}
                </span>
                <span>
                    {{ comment.content }}
                </span>
                <span>
                    {{ comment.createdAt|ago }}
                </span>
                <br>
            </div>
        {% endfor %}

    </div>
{% endblock %}